// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Ahmed_Task.Models;
using Microsoft.EntityFrameworkCore;

namespace Ahmed_Task.Data;

public partial class MedLinkDbContext : DbContext
{
    public MedLinkDbContext(DbContextOptions<MedLinkDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Appointment> Appointments { get; set; }

    public virtual DbSet<City> Cities { get; set; }

    public virtual DbSet<Clinic> Clinics { get; set; }

    public virtual DbSet<Doctor> Doctors { get; set; }

    public virtual DbSet<DoctorAvailability> DoctorAvailabilities { get; set; }

    public virtual DbSet<Governate> Governates { get; set; }

    public virtual DbSet<Location> Locations { get; set; }

    public virtual DbSet<Patient> Patients { get; set; }

    public virtual DbSet<Speciality> Specialities { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Appointment>(entity =>
        {
            entity.HasIndex(e => e.ClinicId, "IX_Appointments_ClinicId");

            entity.HasIndex(e => e.DoctorId, "IX_Appointments_DoctorId");

            entity.HasIndex(e => e.PatientId, "IX_Appointments_PatientId");

            entity.Property(e => e.Price).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.Clinic).WithMany(p => p.Appointments).HasForeignKey(d => d.ClinicId);

            entity.HasOne(d => d.Doctor).WithMany(p => p.Appointments)
                .HasForeignKey(d => d.DoctorId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.Patient).WithMany(p => p.Appointments).HasForeignKey(d => d.PatientId);
        });

        modelBuilder.Entity<City>(entity =>
        {
            entity.HasIndex(e => e.GovernateId, "IX_Cities_GovernateId");

            entity.Property(e => e.Name).IsRequired();

            entity.HasOne(d => d.Governate).WithMany(p => p.Cities)
                .HasForeignKey(d => d.GovernateId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<Clinic>(entity =>
        {
            entity.HasIndex(e => e.DoctorId, "IX_Clinics_DoctorId");

            entity.HasIndex(e => e.LocationId, "IX_Clinics_LocationId");

            entity.HasIndex(e => e.SpecialityId, "IX_Clinics_SpecialityId");

            entity.Property(e => e.Name)
                .IsRequired()
                .HasDefaultValue("");
            entity.Property(e => e.Phone).IsRequired();
            entity.Property(e => e.Price).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.Doctor).WithMany(p => p.Clinics)
                .HasForeignKey(d => d.DoctorId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.Location).WithMany(p => p.Clinics).HasForeignKey(d => d.LocationId);

            entity.HasOne(d => d.Speciality).WithMany(p => p.Clinics).HasForeignKey(d => d.SpecialityId);
        });

        modelBuilder.Entity<Doctor>(entity =>
        {
            entity.HasIndex(e => e.Email, "IX_Doctors_Email").IsUnique();

            entity.HasIndex(e => e.Phone, "IX_Doctors_Phone").IsUnique();

            entity.HasIndex(e => e.SpecialityId, "IX_Doctors_SpecialityId");

            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.FirstName)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.LastName)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(250);
            entity.Property(e => e.Phone)
                .IsRequired()
                .HasMaxLength(25);

            entity.HasOne(d => d.Speciality).WithMany(p => p.Doctors).HasForeignKey(d => d.SpecialityId);
        });

        modelBuilder.Entity<DoctorAvailability>(entity =>
        {
            entity.HasIndex(e => e.ClinicId, "IX_DoctorAvailabilities_ClinicId");

            entity.HasIndex(e => e.DoctorId, "IX_DoctorAvailabilities_DoctorId");

            entity.Property(e => e.Day).IsRequired();

            entity.HasOne(d => d.Clinic).WithMany(p => p.DoctorAvailabilities)
                .HasForeignKey(d => d.ClinicId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.Doctor).WithMany(p => p.DoctorAvailabilities).HasForeignKey(d => d.DoctorId);
        });

        modelBuilder.Entity<Governate>(entity =>
        {
            entity.Property(e => e.Name).IsRequired();
        });

        modelBuilder.Entity<Location>(entity =>
        {
            entity.HasIndex(e => e.CityId, "IX_Locations_CityId");

            entity.HasIndex(e => e.GovernateId, "IX_Locations_GovernateId");

            entity.Property(e => e.PostalCode).IsRequired();
            entity.Property(e => e.Street).IsRequired();

            entity.HasOne(d => d.City).WithMany(p => p.Locations).HasForeignKey(d => d.CityId);

            entity.HasOne(d => d.Governate).WithMany(p => p.Locations).HasForeignKey(d => d.GovernateId);
        });

        modelBuilder.Entity<Patient>(entity =>
        {
            entity.HasIndex(e => e.Email, "IX_Patients_Email").IsUnique();

            entity.HasIndex(e => e.Phone, "IX_Patients_Phone").IsUnique();

            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(250);
            entity.Property(e => e.Phone)
                .IsRequired()
                .HasMaxLength(25);
        });

        modelBuilder.Entity<Speciality>(entity =>
        {
            entity.HasIndex(e => e.Name, "IX_Specialities_Name").IsUnique();

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(150);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}