// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ahmed_Task.Models;

public partial class Appointment
{
    public int Id { get; set; }

    public int PatientId { get; set; }

    public int DoctorId { get; set; }

    public int ClinicId { get; set; }

    public TimeOnly AppointmentStart { get; set; }

    public TimeOnly AppointmentEnd { get; set; }

    public int Status { get; set; }

    public DateOnly Day { get; set; }

    public decimal? Price { get; set; }

    public virtual Clinic Clinic { get; set; }

    public virtual Doctor Doctor { get; set; }

    public virtual Patient Patient { get; set; }
}