// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ahmed_Task.Models;

public partial class City
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int GovernateId { get; set; }

    public virtual Governate Governate { get; set; }

    public virtual ICollection<Location> Locations { get; set; } = new List<Location>();
}