// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ahmed_Task.Models;

public partial class Clinic
{
    public int Id { get; set; }

    public string Phone { get; set; }

    public decimal Price { get; set; }

    public int DoctorId { get; set; }

    public int LocationId { get; set; }

    public string Name { get; set; }

    public int SpecialityId { get; set; }

    public virtual ICollection<Appointment> Appointments { get; set; } = new List<Appointment>();

    public virtual Doctor Doctor { get; set; }

    public virtual ICollection<DoctorAvailability> DoctorAvailabilities { get; set; } = new List<DoctorAvailability>();

    public virtual Location Location { get; set; }

    public virtual Speciality Speciality { get; set; }
}