// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ahmed_Task.Models;

public partial class DoctorAvailability
{
    public int Id { get; set; }

    public string Day { get; set; }

    public TimeOnly AppointmentStart { get; set; }

    public TimeOnly AppointmentEnd { get; set; }

    public int DoctorId { get; set; }

    public int ClinicId { get; set; }

    public virtual Clinic Clinic { get; set; }

    public virtual Doctor Doctor { get; set; }
}