// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ahmed_Task.Models;

public partial class Location
{
    public int Id { get; set; }

    public string Street { get; set; }

    public string PostalCode { get; set; }

    public int GovernateId { get; set; }

    public int CityId { get; set; }

    public virtual City City { get; set; }

    public virtual ICollection<Clinic> Clinics { get; set; } = new List<Clinic>();

    public virtual Governate Governate { get; set; }
}